<div class="bg-white" data-content-type="div" data-appearance="default" data-element="main">
    <div class="testimonials-container" data-content-type="teague_testimonials" data-appearance="default" data-element="main">
        <div class="max-w-screen-xl mx-auto">
            <div class="overflow-x-auto">
                <div class="flex flex-row flex-nowrap md:grid md:grid-cols-3 md:gap-0 lg:gap-28">
                    <div class="min-w-[16.5rem] md:min-w-0 text-center px-6 md:px-7 lg:px-8 py-brand-90 md:py-26 flex flex-col flex-no-wrap justify-between">
                        <p class="quote block italic mb-8 text-[#100602] font-medium text-xl"><?php echo $block->getData('widgetquote-text1'); ?></p>
                        <div>
                            <p class="body-small text-[#100602] testimonials-author-name-one" data-element="author_name_one"><?php echo $block->getData('widget-author1'); ?></p>
                            <p class="body-small text-gray-700 font-light testimonials-author-title-one" data-element="author_title_one"><?php echo $block->getData('widget-company-name1'); ?></p>
                        </div>
                    </div>

                    <div class="min-w-[16.5rem] md:min-w-0 text-center px-6 md:px-7 lg:px-8 py-brand-90 md:py-26 flex flex-col flex-no-wrap justify-between">
                        <p class="quote block italic mb-8 text-[#100602] font-medium text-xl testimonials-review-two" data-element="review_two"><?php echo $block->getData('widgetquote-text2'); ?></p>
                        <div>
                            <p class="body-small text-[#100602] testimonials-author-name-two" data-element="author_name_two"><?php echo $block->getData('widget-author2'); ?></p>
                            <p class="body-small text-gray-700 font-light testimonials-author-title-two" data-element="author_title_two"><?php echo $block->getData('widget-company-name2'); ?></p>
                        </div>
                    </div>

                    <div class="min-w-[16.5rem] md:min-w-0 text-center px-6 md:px-7 lg:px-8 py-brand-90 md:py-26 flex flex-col flex-no-wrap justify-between">
                        <p class="quote block italic mb-8 text-[#100602] font-medium text-xl testimonials-review-three" data-element="review_three"><?php echo $block->getData('widgetquote-text3'); ?></p>
                        <div>
                            <p class="body-small text-[#100602] testimonials-author-name-three" data-element="author_name_three"><?php echo $block->getData('widget-author3'); ?></p>
                            <p class="body-small text-gray-700 font-light testimonials-author-title-three" data-element="author_title_three"><?php echo $block->getData('widget-company-name3'); ?></p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>